### ISSUE TITLE
Recettes : Recherche et gestion par nb personnes

### ISSUE THREAD

**Issue by Trystan4** [RomainVacheret/Wadge-FrontEnd#100]
~~Rechercher  les recettes de Marmiton en fonction d'un nombre de personnes (pour les recettes) donné par l'utilisateur.~~
Filtre les recettes affichées en fonction de la valeur entrée dans la barre de recherche.
**Coût : 3 -> 1**

**Comment by FannyLourioux** [comment]
C

**Comment by FannyLourioux** [comment]
Closed by #353642d966644970825b5d55515f460c93a19d0
