### ISSUE TITLE
Recettes (IHM) : Couleur en fonction du frigo

### ISSUE THREAD

**Issue by RomainVacheret** [RomainVacheret/Wadge-FrontEnd#116]
Différentes couleurs pour les recettes en fonction de leur statut dans le frigo :
* Orange : possédé mais pas assez
* Rouge : pas possédé
* Vert possédé
* Noir : ne fait pas parti des aliments répertoriés

** Coût : 3 **

**Comment by FannyLourioux** [comment]
Closed by 835d0e6e431540c7db0c403a5ff72c48baa6e9b1
