### ISSUE TITLE
Recettes : Création de liste de course à partir d'une recette

### ISSUE THREAD

**Issue by RomainVacheret** [RomainVacheret/Wadge-FrontEnd#117]
Création d'une liste de course à partir des aliments qui ne sont pas possédés / pas en assez grande quantité.
Possibilité d'exporter cela dans une application de TODO liste.

** Coùt : 8**

**Comment by FannyLourioux** [comment]
Closed by 42651394f18f0de62a9a425dafa678ff1b21e914
