### ISSUE TITLE
Recenser les fruits et légumes possédés

### ISSUE THREAD

**Issue by RomainVacheret** [RomainVacheret/Wadge-FrontEnd#12]
L'utilisateur peut sélectionner les fruits et légumes qu'il a dans son frigo.
Ses informations sont stockées.

###  ** Coût : 5**
- [x] Back
- [x] Front

**Comment by FannyLourioux** [comment]
Closed by #e1bba8f95c1bdec3568d971ccc2cb20feaf9cd90
