### ISSUE TITLE
Liste des magasins proches

### ISSUE THREAD

**Issue by RomainVacheret** [RomainVacheret/Wadge-FrontEnd#14]
Les magasins Naturalia présents sur la carte ne sont plus toujours les mêmes.
Ils sont récupérés en fonction de la position de l'utilisateur.
Leur adresse est affichée, de même.
Affichage pour chaque magasin s'il est actuellement ouvert ou non.

Notes : 
L'utilisateur doit accepter de partager sa position 
Les magasins référencés doivent être à 2 km maximum de la position de l'utilisateur

### **Coût : 3 -> 3**

**Comment by FannyLourioux** [comment]
Closed by #7abf77c1ea83fc9ec5b7a3e454c13e1cd1d581ff
