### ISSUE TITLE
Affichage plus agréable pour les aliments

### ISSUE THREAD

**Issue by RomainVacheret** [RomainVacheret/Wadge-FrontEnd#45]
L'affichage consiste en :
* Un carré avec une couleur de fond en lieu avec l'aliment
* Au centre du carré, la première lettre du mot en majuscule suivie de la seconde en minuscule
* En bas du carré, le mot en entier en police plus petite

** Coût 2 **

**Comment by FannyLourioux** [comment]
Closed by #4c21e8b74409f0ee18cb64a2f78c97ac2d264941
