### ISSUE TITLE
Alertes pour les produits qu'il faut consommer rapidement

### ISSUE THREAD

**Issue by RomainVacheret** [RomainVacheret/Wadge-FrontEnd#9]
Liste des produits possédés à consommer avant  une ou plusieurs échéances données.
Les échéances sont :
* Déjà expiré
* 2 jours
* 5 jours
* 7 jours
* 14 jours
### **Coût : 3 -> 5**
- [x] Front
- [x] Back

**Comment by FannyLourioux** [comment]
Closed by #0c5288b3490b2e06d2bbe0b91333d8e2eb67fa84
