### ISSUE TITLE
Recettes (IHM) : Marquage ingrédients possédés

### ISSUE THREAD

**Issue by RomainVacheret** [RomainVacheret/Wadge-FrontEnd#95]
Dans la carte d'une recette, les ingrédients sont affichés de différentes couleurs :
* Possédées
* Non possédées
* Pas pris en compte dans le frigo

** coût : 3 **

**Comment by FannyLourioux** [comment]
Closed by 9b10d38b9c9d633bf4814f20540e7eda478bb4eb
