### ISSUE TITLE
Recettes (IHM) : Suppression ingrédients par l'utilisateur

### ISSUE THREAD

**Issue by RomainVacheret** [RomainVacheret/Wadge-FrontEnd#96]
Lorsque l'utilisateur a fini de faire une recette, il choisit quelle quantité de chaque aliment il souhaite enlever du frigo. 

** Coût : 2 **

**Comment by FannyLourioux** [comment]
closed by 4f123acdaf99f5335ac327c2cb45caaf31d7c046
