### ISSUE TITLE
Recettes (IHM) : Recherche plusieurs aliments à la fois

### ISSUE THREAD

**Issue by RomainVacheret** [RomainVacheret/Wadge-FrontEnd#99]
Quand l'utilisateur cherche des recettes avec plusieurs aliment, plante au niveau du front.
`unhandled Rejection (TypeError): response is not iterable`
Reproduire :
Entrer ` tomate,carotte`

** Coût : 1 **

**Comment by FannyLourioux** [comment]
Closed by cd90e142ee41c83c18323b9879e7b13808fa4fa7
